name: build
on: [push, pull_request]
# on:
# push:
#   branches:
#     - master
#     - 'v*.*.*'
jobs:
  run-tests:
    name: Build and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['10.x', '12.x', '14.x', '16.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm i -g yarn
      - run: yarn install
      - run: npm run test:cov
      - name: Codecov
        uses: codecov/codecov-action@v3.1.1
      - run: npm run benchmark

