name: tests
on: [push, pull_request]
# on:
# push:
#   branches:
#     - master
#     - 'v*.*.*'
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm i -g yarn
      - run: yarn install
      - run: npm run test:cov
      - run: npm run benchmark
